---
name: Demo App
description: >
  testing app for catalog.
version: v0.1
category: Testing
maintainer: Daniel Monteiro <daniel.monteiro@alfresco.com>
license: Apache2
projectURL: https://github.com/dmonteiro-alfresco/rancher-cattle-demo